### ISSUE TITLE
ActionBar Duplicates Actions (Grid Model)

### ISSUE THREAD

**Issue by mfinley** [qgrid/ng2#442]
Issue:   When the grid model is destroyed and recreated the action bar is duplicated.  

Example:  https://qgrid.github.io/ng2/destroy-grid-model?search=des 

Note: Using the model in a grid detail row creates new actions for every detail expansion which is to be expected.  
 
![ActionDuplicate](https://user-images.githubusercontent.com/20345249/64873320-68581500-d60e-11e9-9dfa-3f774511f052.png)

**Comment by klumba12** [comment]
Thank you! Is it still a critical issue for you?
