### ISSUE TITLE
@qgrid/ngx: error: Invalid version: "15.2-15.3" while building qgrid/ngx as of 6/1 Master branch

### ISSUE THREAD

**Issue by Domush** [qgrid/ng2#619]
Getting a build error for @qgrid/ngx using the current Master:

![image](https://user-images.githubusercontent.com/1557976/171442058-ff33fa6c-d85c-4669-ad78-8cb4b39ac2a4.png)

Any workaround for this? I have a grid project coming due using Angular v13 and would really like to use this grid for it, but so far I haven't been able to get any qgrid version (even alpha builds) to work using v13 of Angular.

If someone can share a package.json which makes an npm version of qgrid work w/v13 of Angular I'd appreciate it.

Cheers

**Comment by klumba12** [comment]
Hey, version 13.3.0 was released, you can try that.
